name: Build, publish and deploy a docker image

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to github registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        uses: docker/metadata-action@v3
        id: meta_spaceport_backend
        with:
          images: ghcr.io/spaceport-near/backend

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta_spaceport_backend.outputs.tags }}
          labels: ${{ steps.meta_spaceport_backend.outputs.labels }}

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Deploy image to cluster
        uses: actions-hub/kubectl@v1.25.4
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment/spaceport-backend-backend
